version: '3.5'
services:
  ds:
    image: ds-simple-mock:1.0.0
    build: .
    container_name: ds
    hostname: ds
    networks:
      - ds-network

networks:
  ds-network:
    external:
      name: three-ds-network
